### PR TITLE
Add reprs and use f-strings

### PR DESCRIPTION
**Pull request by akaIDIOT**

### CODE REVIEW

**Comment by bartbroere** [comment]
I got the feeling that some people (we might know) using Ubuntu 16's default ``python3.5`` might get an unpleasant surprise, but I'm sure they'll find out what caused it. Or was Python 3.6 already required for different reasons in this project?

To be sure I checked some common libraries we tend to use whether they still require Python 3.5 only, but none do fortunately. Although this was more than two years ago, very data sciency issues like this existed: https://stackoverflow.com/questions/46842398/is-it-true-that-tensorflow-only-work-on-python3-5-2

This would prevent our projects from using a combination of ``confidence`` and these libraries, but is not the case 👍

**Review by bartbroere — APPROVED** [review]
More readable code!

**Comment by akaIDIOT** [comment]
I was scared there for a bit, but luckily, from [PEP-0478](https://www.python.org/dev/peps/pep-0478/):

> Note that Python 3.5 will no longer be supported after September 2020. Therefore, 3.5.10 may be the final release of Python 3.5.

Though that states *after* september, so maybe wait with a release for this feature until October O:)

**Comment by bartbroere** [comment]
> so maybe wait with a release for this feature until October O:)

Yeah, why not. Waiting is free

**Pull request merged**
